site_name: KTHub Docs
site_description: Welcome to the KTHub documentation.
site_url: https://KTHub.io/

site_author: Sadhvik Chirunomula
repo_url: "https://github.com/KnowledgeTransferHub/Workshops-Wiki"
copyright: "KTHub is licensed under MIT"

theme:
  name: material
  colorscheme: dracula
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - shell
    - bash

nav:
  - Home: index.md
  - Docs:
    - 2-Day-Worshop-on-Full-Stack-Development: 2-Day-Worshop-on-Full-Stack-Development/README.md
    - 2-Day-Workshop-on-Front-End-Development: 2-Day-Workshop-on-Front-End-Development/README.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
